version: "3.9"

services:
  web:
    build: .
    container_name: toxic-comments-app
    restart: always
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: toxic-comments-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toxic-comments
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: toxic-comments-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - FASTAPI_SERVICE_URL=${FASTAPI_SERVICE_URL}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    depends_on:
      - web
